version: '3.8'

services:
  # Banco relacional para dados transacionais (Ordens e Usuários)
  postgres:
    image: postgres:15
    container_name: os_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  # Banco NoSQL para logs e histórico (Audit Service)
  mongodb:
    image: mongo:latest
    container_name: os_mongodb
    restart: always
    ports:
      - "27017:27017"

  # Message Broker para comunicação entre serviços
  rabbitmq:
    image: rabbitmq:3-management
    container_name: os_rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Porta do protocolo AMQP (mensageria)
      - "15672:15672" # Painel administrativo (UI)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest